### ISSUE TITLE
JSON ValueError exception

### ISSUE THREAD

**Issue by xandr2** [abourguignon/jinja2-live-parser#5]
Hi when I have an error in my JSON values script doesn't show anything about it just not work. I try to handle and show this error but it doesn't work. Can you help?

```
    if bool(int(request.form['dummyvalues'])):
        # List variables (introspection)
        env = Environment()
        vars_to_fill = meta.find_undeclared_variables(env.parse(request.form['template']))
        for v in vars_to_fill:
            values[v] = choice(dummy_values)
    else:
        try:
            values = json.loads(request.form['values'])
        except ValueError as e:
            rendered_tpl = "Value error in JSON: {0}".format(e)
            return rendered_tpl
```

**Comment by abourguignon** [comment]
Hello, 

Indeed, the parser doesn't integrate any json validator of any kind.  This is not foreseen but I would definitely integrate any pull request going that direction.  In the meantime you'll have to rely on another solution to validate your json input.
