### ISSUE TITLE
readme has incorrect port if using docker

### ISSUE THREAD

**Issue by patapra** [abourguignon/jinja2-live-parser#6]
theres a minor oversight in your readme. if you pull your project from the docker registry with:

> docker run -d -p 49153:5000 sahilsk/j2parser

the port to access it will be 49153, not 5000.

> You are all set, go to http://localhost:5000/ and have fun.

thanks for this project!

**Comment by abourguignon** [comment]
Hello, 

Sorry about that.  I suggest a simple 5000 to 5000 mapping then: 

> docker run -d -p 5000:5000 sahilsk/j2parser

Sounds good to you ?

**Comment by patapra** [comment]
sure. thanks!
